#!/usr/bin/env bash
# Installs nginx, serves a page containing "Holberton School", configures the
# /redirect_me 301 redirect, and sets up a custom 404 page that contains the
# string "Ceci n'est pas une page".

apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/listen 80 default_server;/a\
\tlocation /redirect_me {\
\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
\t}\
\
\terror_page 404 /404.html;\
\tlocation = /404.html {\
\t\troot /var/www/html;\
\t\tinternal;\
\t}' /etc/nginx/sites-available/default

service nginx start
service nginx restart
